### ISSUE TITLE
拉取项目启动直接：Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup

### ISSUE THREAD

**Issue by 2565911151** [yeecode/ObjectLogger#43]
拉取项目后直接启动，没做任何配置，堆栈错误如下：
Connected to the target VM, address: '127.0.0.1:2403', transport: 'socket'

. ____ _ __ _ _
/\ / ' __ _ () __ __ _ \ \ \
( ( )__ | '_ | '| | ' / ` | \ \ \
\/ )| |)| | | | | || (| | ) ) ) )
' || .__|| ||| |_, | / / / /
=========||==============|/=////
:: Spring Boot :: (v2.1.6.RELEASE)

2024-03-28 10:42:11.759 ERROR 13676 --- [ main] o.s.boot.SpringApplication : Application run failed

org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.18.jar:5.3.18]
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:146) ~[spring-beans-5.3.18.jar:5.3.18]
at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:583) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
at com.github.yeecode.objectlogger.server.ObjectLoggerServerApplication.main(ObjectLoggerServerApplication.java:12) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
at org.springframework.context.support.AbstractApplicationContext.(AbstractApplicationContext.java:229) ~[spring-context-5.3.18.jar:5.3.18]
at org.springframework.context.support.GenericApplicationContext.(GenericApplicationContext.java:112) ~[spring-context-5.3.18.jar:5.3.18]
at org.springframework.web.context.support.GenericWebApplicationContext.(GenericWebApplicationContext.java:97) ~[spring-web-5.3.18.jar:5.3.18]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.(ServletWebServerApplicationContext.java:114) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
at org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext.(AnnotationConfigServletWebServerApplicationContext.java:72) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_381]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_381]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_381]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_381]
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.18.jar:5.3.18]
... 6 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_381]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_381]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_381]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_381]
... 16 common frames omitted

**Comment by 2565911151** [comment]
Connected to the target VM, address: '127.0.0.1:2403', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.6.RELEASE)

2024-03-28 10:42:11.759 ERROR 13676 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:146) ~[spring-beans-5.3.18.jar:5.3.18]
	at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:583) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at com.github.yeecode.objectlogger.server.ObjectLoggerServerApplication.main(ObjectLoggerServerApplication.java:12) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
	at org.springframework.context.support.AbstractApplicationContext.<init>(AbstractApplicationContext.java:229) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.GenericApplicationContext.<init>(GenericApplicationContext.java:112) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.web.context.support.GenericWebApplicationContext.<init>(GenericWebApplicationContext.java:97) ~[spring-web-5.3.18.jar:5.3.18]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.<init>(ServletWebServerApplicationContext.java:114) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext.<init>(AnnotationConfigServletWebServerApplicationContext.java:72) ~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_381]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_381]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_381]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_381]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.18.jar:5.3.18]
	... 6 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_381]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_381]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_381]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_381]
	... 16 common frames omitted
